version: "3"

tasks:

  build:
    desc: "Сборка контейнера с сервисом"
    cmds:
      - docker build -t app .

  start:
    desc: "Сборка и запуск контейнера с сервисом"
    deps: [build]
    cmds:
      - docker run --rm -p 8501:8501 app:latest